"""
Feature group definitions for UCI Adult Income dataset.
Auto-generated by clean_adult.py
"""

GROUP_A = ['age', 'female', 'education_num']
GROUP_B = ['hours_per_week', 'government', 'self_employed', 'white_collar', 'blue_collar', 'service']
GROUP_C = ['capital_gain', 'capital_loss', 'married']
OUTCOME = "income"
CATEGORICAL_FEATURES = ['female', 'government', 'self_employed', 'white_collar', 'blue_collar', 'service', 'married']

SPECIFICATIONS = {
    "A":   GROUP_A,
    "AB":  GROUP_A + GROUP_B,
    "AC":  GROUP_A + GROUP_C,
    "ABC": GROUP_A + GROUP_B + GROUP_C,
}
