"""
Feature group definitions for UCI Credit Card Default dataset.
Auto-generated by clean_credit_default.py
"""

GROUP_A = ['age', 'female', 'education', 'married']
GROUP_B = ['avg_pay_status', 'months_delayed']
GROUP_C = ['avg_bill_amt', 'avg_pay_amt', 'pay_ratio']
OUTCOME = "default"
CATEGORICAL_FEATURES = ['female', 'married']

SPECIFICATIONS = {
    "A":   GROUP_A,
    "AB":  GROUP_A + GROUP_B,
    "AC":  GROUP_A + GROUP_C,
    "ABC": GROUP_A + GROUP_B + GROUP_C,
}
