"""
Feature group definitions for Ames Housing dataset.
Auto-generated by clean_ames_housing.py
"""

GROUP_A = ['GrLivArea', 'BedroomAbvGr', 'FullBath', 'HalfBath']
GROUP_B = ['OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd']
GROUP_C = ['LotArea', 'GarageArea', 'nbhd_high', 'nbhd_mid']
OUTCOME = "SalePrice"
CATEGORICAL_FEATURES = ['nbhd_high', 'nbhd_mid']

SPECIFICATIONS = {
    "A":   GROUP_A,
    "AB":  GROUP_A + GROUP_B,
    "AC":  GROUP_A + GROUP_C,
    "ABC": GROUP_A + GROUP_B + GROUP_C,
}
